### ISSUE TITLE
Static linking

### ISSUE THREAD

**Issue by mintty** [Biswa96/wslbridge2#4] opened 2019-09-05 08:20 UTC
In order to support WSL distros with different runtime environments, it would be better to have the backend statically linked (mintty/wsltty#156).
That probably also needs the getpwuid patch that wsltty currently adds to wslbridge(1).

**Comment by Biswa96** [comment] 2019-09-05 08:45
How about shipping two backend binaries? VSCode does this, one for Alpine and another for Debian and it's children.

**Comment by mintty** [comment] 2019-09-05 08:49
That would make 4 backends (2 for wslbridge2 and 2 for hvpty) but that's not the problem.
The problem is to determine which one has to be invoked for a given distribution...

**Comment by Biswa96** [comment] 2019-09-08 09:34
How about copy the `getpwuid(3)` code from glibc or ulibc and use them directly? Or remove the `getpwuid(3)` completely and use `$SHELL` environment variable to get the running shell?

**Comment by Biswa96** [comment] 2019-09-08 09:40
* How about copy the `getpwuid(3)` code from glibc or ulibc and use them directly?
* Or remove the `getpwuid(3)` completely and use `$SHELL` environment variable to get the running shell?
* Or not using `-static` option at all and provide all the required library in the package?

**Comment by mintty** [comment] 2019-09-08 16:34
> * How about copy the getpwuid(3) code from glibc or ulibc and use them directly?

If you'd like to investigate on this... Calling the code, however, needs dynamic linking (for whatever reason), so I'd assume just copying it may have the same requirement.

> * Or remove the getpwuid(3) completely and use $SHELL environment variable to get the running shell?

It's only the shell itself that sets $SHELL in the first place...

> * Or not using -static option at all and provide all the required library in the package?

If you'd like to investigate on this... Maybe possible but could also require a lot of dependent libraries. Furthermore, I'm not sure this would really run with other distributions.

**Comment by Biswa96** [comment] 2019-09-08 16:58
> It's only the shell itself that sets $SHELL in the first place...

That's true in *nix world. In WSL, `/init` does that.

**Comment by Biswa96** [comment] 2019-09-08 18:09
> It's only the shell itself that sets $SHELL in the first place...

That's true in *nix world. In WSL, `/init` does that. @therealkenc Is it reliable to replace `getpwuid(3)` with `getenv("SHELL")` in both backends?

**Comment by mintty** [comment] 2019-09-09 02:16
> In WSL, /init does that.

Is that behaviour documented somewhere? Might be an option then.

**Comment by Biswa96** [comment] 2019-09-09 04:03
If everything is documented about WSL anyone can create their own wslbridge 😎

**Comment by Biswa96** [comment] 2019-09-09 05:12
Don't know if this is documented or not.

**Comment by therealkenc** [comment] 2019-09-09 08:31
I haven't been following the other thread. If WSL `init/` sets the `$SHELL` variable before spawning the shell, that would be "odd". I won't say it doesn't. But I wouldn't depend on that. Musl has a `getpwuid(3)` implementation ([here](https://github.com/bminor/musl/blob/05ac345f895098657cf44d419b5d572161ebaf43/src/passwd/getpw_a.c#L20)). Build the thing static under Alpine, it'll run everywhere.

**Comment by mintty** [comment] 2019-09-09 11:35
The attached patch should make it work based on $SHELL.

[0001-static-linking-discard-getpwuid.patch.txt](https://github.com/Biswa96/wslbridge2/files/3590233/0001-static-linking-discard-getpwuid.patch.txt)

But I'll also try the suggestion to link statically on musl, with getpwuid. If it works, it will be the nicer solution.

**Comment by Biswa96** [comment] 2019-09-09 13:25
Did you try the patch in Alpine with ash shell? I have done similar thing but alpine does not show up in hvpty. wslbridge2 works well with it.

**Comment by mintty** [comment] 2019-09-09 17:01
> Build the thing static under Alpine

That'll need a bunch of work:
```
SocketIo.cpp: In function 'std::__cxx11::string errorString(BridgedError)':
SocketIo.cpp:152:30: error: invalid conversion from 'int' to 'char*' [-fpermissive]
     char *errStr = strerror_r(bridgedErrno, buf, sizeof(buf));
                    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hvpty-backend.cpp:23:10: fatal error: linux/vm_sockets.h: No such file or directory
 #include <linux/vm_sockets.h>
          ^~~~~~~~~~~~~~~~~~~~
```

**Comment by mintty** [comment] 2019-09-09 17:06
> Did you try the patch in Alpine with ash shell?

Yes, it works with wslbridge2.

> I have done similar thing but alpine does not show up in hvpty.

You mean, after `wsl --set-version Alpine 2`?

**Comment by Biswa96** [comment] 2019-09-09 17:09
> You mean, after wsl --set-version Alpine 2?

Yes, obviously. Also you'll need `linux-headers` package. Command: `apk add linux-headers`.

**Comment by mintty** [comment] 2019-09-09 17:19
No, Alpine WSL 2 does not work with hvpty built statically with libc.
How do I install a package in Alpine?

**Comment by Biswa96** [comment] 2019-09-09 17:20
Command: `apk add linux-headers`.

**Comment by mintty** [comment] 2019-09-09 17:45
> No, Alpine WSL 2 does not work with hvpty built statically with libc.

And it does not work with hvpty built statically in Alpine...
And it does not work with unpatched hvpty, built dynamically in Alpine...

**Comment by Biswa96** [comment] 2019-09-10 19:26
Thank you. I tried your patch. It works well with WSL1 part. I tried WSL2 part with Void Linux rootfs which also uses musl libc. hvpty works there but not with Alpine. So, the issue is not the libc. I did not find any signifcant error in strace. Investigating...

**Comment by Biswa96** [comment] 2019-09-13 08:24
I want to modify the makefile not to build static linked binary always. For example, make command will create binary without static options but `make release` will create static linked binaries. Will this be any issue for mintty/wsltty?

**Comment by mintty** [comment] 2019-09-14 08:41
My current picture is this: static linking with the current version, whether built on Ubuntu or Alpine, runs almost everywhere, except hvpty on Alpine/WSL 2.
Is there a problem with any other distribution? (Asking for the README of the next wsltty release.)

**Comment by Biswa96** [comment] 2019-09-15 18:32
Update: The errors seem to be in the `poll(2)` loop in hvpty-backend. Investigating...

**Comment by Biswa96** [comment] 2019-09-22 04:13
Update: In Alpine, if I pause the backend program and enter the `initPort` manually hvpty works as usual. My query, is there any difference in `recv(2)` and `send(2)` mechanism between Alpine and other distros?

**Comment by mintty** [comment] 2019-09-23 15:37
How would you pause the backend program? Can you add details?

**Comment by Biswa96** [comment] 2019-09-23 15:42
I will add a `--debug` option (or something like it) to tinkering. 

Another issue, wslbridge2 has a regression. It shows connection broken when `--static` is used. May be an undefined behaviour. This static linking makes me mad... 🤪

**Comment by Biswa96** [comment] 2019-09-23 15:43
I will add a `--debug` option (or something like it) to tinkering. 

Another issue, wslbridge2 has a regression. It shows connection broken when `--static` is used with glibc _only_ (musl ok). May be an undefined behaviour. This static linking makes me mad... 🤪

**Comment by therealkenc** [comment] 2019-09-23 16:43
> This static linking makes me mad... 🤪

Stayed quiet because I'm at a loss too 🤷. Something very subtle is going on because there is very little that is "Alpine" about a static build (hesitate to say "nothing" only for risk of missing something). The program is making raw syscalls (like `recv(2)` and `send(2)`), and the kernel is **identical** between a Ubuntu run and an Alpine run. Normally with this sort of problem it would be a difference in the kernel shipped with the distro, but that is (uncharacteristically) not the problem here because the kernels are the same, and it works on Ubuntu.

Static GNU glibc is a fools errand. That it _does not_ work with a _dynamic_ (sic) Alpine musl build is the thread I would start tugging. Perhaps make an absolutely minimal test case exercising VM sockets (think 'gist') and maybe you can get some eyeballs on it from the Alpine community (wherever they hang out).  It might be obvious to them.

One rando closing thought. Be very careful with the Linux kernel headers. You can't (well, shouldn't) use the headers from `apk add linux-headers` because those are "wrong" for your kernel. Your kernel is `4.19.67-microsoft-standard` not the one Alpine (or Ubuntu) ships. You can use stock Linux 4.19.67 or Microsoft's headers; they are the same AFAIK. The kernel ABI is usually stable enough between kernels that it doesn't matter, but in this case we are running out of other things to point the finger. I don't actually think this will work, but if you are shipping a static binary, it is best to take a local linux-kernel header dependency in the project when coding this close to the metal. [This is why people naively trying to compile graphics drivers in WSL Ubuntu complain their headers are missing.] In extremis you should be building your own musl against those headers too and use `musl-gcc(1)` to compile. 

Again I am skeptical this is going to help, because if it were the ABI you should be seeing grief on Ubuntu. It's just an idle observation. Apologies I can't dive this myself. Normally I would, because it is an interesting problem; but I'm eyeballs deep in something else atm.

**Comment by Biswa96** [comment] 2019-09-23 17:16
Thanks for the comments. I didn't consider those variables...

> Perhaps make an absolutely minimal test case exercising VM sockets

This repo has some test files in hvsocket folder.

> Be very careful with the Linux kernel headers. 

The hvpty only imports some defined constants and `struct sockaddr_vm`. I have check those in Ubuntu and Alpine `/usr/include/linux/vm_sockets.h` file and those are same. The `vm_sockets.h` file can be added in this repo if license allows.

**Comment by Biswa96** [comment] 2019-09-23 19:13
@mintty Apply this patch file. Run hvpty.exe in mintty. Copy the port number. Open wsl.exe with Alpine in WSL2, run hvpty-backend. It will ask the port number. Paste the port number from frontend.

[hvpty.patch.txt](https://github.com/Biswa96/wslbridge2/files/3643731/hvpty.patch.txt)

This is a temporary comment. Do not use this in future.

**Comment by Biswa96** [comment] 2019-09-26 13:14
If anyone want to dig into the wslbridge-glibc-static bug (as stated before), here is the kernel mode logs from LxCore driver [lxcore-wslbirdge-log.txt](https://github.com/Biswa96/wslbridge2/files/3657894/lxcore-wslbirdge-log.txt).

**Comment by Biswa96** [comment] 2019-09-26 13:15
If anyone want to dig into the wslbridge-glibc-static bug (as stated before), here is the kernel mode logs from LxCore driver [lxcore-wslbirdge-log.txt](https://github.com/Biswa96/wslbridge2/files/3657894/lxcore-wslbirdge-log.txt).

This is a temporary comment. Do not use this in future.

**Comment by Biswa96** [comment] 2019-09-27 13:06
The hvpty issue in WSL2/Alpine seems to be from 9P server in WSL2. If I move the hvpty-backend to WSL territory then execute hvpty, it works fine. This is the sample diff:

```diff
-    wslCmdLine.append(L"\"$(wslpath -u");
-    appendWslArg(wslCmdLine, backendPathWin);
-    wslCmdLine.append(L")\"");
+    wslCmdLine.append(L"/home/user/hvpty-backend");
```

Related to this issue `https://github.com/microsoft/WSL/issues/4377`.

**Comment by mintty** [comment] 2019-09-27 13:27
Ah, we had a similar situation before, in the context of wsltty.appx.
If it's easy to detect a failed backend invocation, the frontend could fix it by invoking something like `wsl cp wsltty-installdir/bin/hvpty-backend /bin` and then retry. (Same for wslbridge2 in case it's ever needed.) If it succeeds, it's a one-time on-demand deployment.

**Comment by Biswa96** [comment] 2019-09-27 13:51
Just waiting for next Insider build... 😴

**Comment by mintty** [comment] 2019-09-27 14:31
OK, if you expect that to work with the current wslbridge2, no change is needed.

**Comment by mintty** [comment] 2019-09-27 14:45
Can you make a release then, or are you still working on the "connection broken" issue? Maybe the frontend could just be silent about that message after the connection terminates?

**Comment by Biswa96** [comment] 2019-09-27 15:07
Most of the people uses Ubuntu. So static linking isn't an issue in Debian family or distros uses glibc by default. The released binaries in this repo's release page work as usual.

**Comment by mintty** [comment] 2019-09-27 15:19
Yes but we considered this before. If you want to deploy dual-mode binaries (dynamic for glibc and static for musl), we'd need to find out how to distinguish them at runtime.

**Comment by Biswa96** [comment] 2019-09-27 15:36
I didn't said about it. See the release page https://github.com/Biswa96/wslbridge2/releases. Only glibc, no static.

**Comment by Biswa96** [comment] 2019-09-28 20:26
Try hvpty now.

**Comment by mintty** [comment] 2019-09-29 02:13
It works with Alpine, good. But not with others (VoidMusl not yet checked).
So how could I integrate that with wsltty?
Any chance, for example by looking into the filesystem or registry, to identify a distribution as musl-based?

**Comment by Biswa96** [comment] 2019-09-29 04:26
> But not with others

I have tested hvpty in Ubuntu, Arch, Debian, Alpine, Void. No issue.

> So how could I integrate that with wsltty?

Wait another bug is with wslbridge2+glibc+static linking.

**Comment by Biswa96** [comment] 2019-09-29 04:31
> But not with others

I have tested hvpty in Ubuntu, Arch, Debian, Alpine, Void. No issue.

> So how could I integrate that with wsltty?

Just compile everything with `make RELEASE=1` and musl libc.

**Comment by mintty** [comment] 2019-09-29 07:52
Oh, RELEASE=1 adds -static, I thought that would be the default now (was it in a previous version?).
Anyway, it works now, great!

So I'll prepare a wsltty release; can you define a wslbridge2 release please? (So I don't have to fiddle with commit downloads.)

**Comment by Biswa96** [comment] 2019-09-29 17:25
@mintty Done.

**Comment by mintty** [comment] 2019-10-01 12:04
I was looking out for v0.4 as I thought to have seen v0.3 before. Did you replace a previous v0.3?

**Comment by Biswa96** [comment] 2019-10-01 12:06
Yes. v0.4 is for a big change. I'll discuss that later.

**Closed as completed** 2019-10-07 15:38 UTC
Labels: bug :bug:

**Comment by Biswa96** [comment] 2019-10-07 15:39
The static linking is now possible but with glibc it produces error. See this issue https://github.com/Biswa96/wslbridge2/issues/15.
