### ISSUE TITLE
wslbridge2 can't start multiple session simultaneously 

### ISSUE THREAD

**Issue by sarim** [Biswa96/wslbridge2#24] opened 2020-06-08 21:51 UTC
Ex If I use conemu to open 3 tabs at startup. First tab opens normally, but the other ones show this error

```
assertion "listenRet == 0" failed: file "WindowsSock.cpp", line 131, function: int ListenHvSock(size_t, const GUID*, int)
```

cmd is `wslbridge2.exe -l -eConEmuBuild -eConEmuPID -eConEmuServerPID -e WSL_HOST_IP`

**Comment by Biswa96** [comment] 2020-06-09 03:40
I've never used ComEmu, mintty fits well in my routine. So need some info about those parameters.

**Comment by sarim** [comment] 2020-06-09 11:48
okey, here's how to reproduce it in wsltty. Ready your fingers, hold down `Alt` and mash `F2` as fast as you can. Imagine you mash it 10 times in 100ms. You'll see ~4 windows open, shows the error i mentioned above and close. 6 window opened successfully.

Its not related to conemu. Its just that if multiple wslbridge2 session tries to start simultaneously, somehow it breaks.  I guess the opening the hv socket and doing initialization stuff takes a second, and if you open another terminal in that time, the next ones fail.

Here is demonstration screen capture video : https://gfycat.com/niceboldfirefly

And a screenshot:

![wsltty-multiple mp4_20200609_174658 795](https://user-images.githubusercontent.com/1235888/84143988-527e6000-aa79-11ea-9ef2-7a188c0d443d.png)

**Comment by sarim** [comment] 2020-06-09 11:59
``` cpp
    while (nretries < BIND_MAX_RETRIES)
    {
        port = RANDOMPORT();
        addr.ServiceId.Data1 = port;
        const int bindRet = bind(sock, (sockaddr*)&addr, sizeof addr);
        if (bindRet == 0)
            break;

        nretries++;
    }

    const int listenRet = listen(sock, backlog);
    assert(listenRet == 0);
```

I guess the error is in RANDOMPORT? the rand() call maybe not returning proper random ports? you're calling `srand(time(NULL))`, but `time(NULL)` will return same second value if it started in same second, not randomized seed. Probably need to get a nanosecond time? or get something from /dev/random ? Also it might be beneficial to add a delay of (n*10ms) after say 5 retries.

Obviously all of this is guesswork. I don't understand much about underlying codes here.

**Comment by Biswa96** [comment] 2020-06-09 12:51
Understood the issue.

**Comment by silverqx** [comment] 2020-07-10 13:46
I can confirm this, if I have opened more tabs eg 4 tabs with wsl2 and close whole cmder window and reopen cmder, so only first tab opens successfully, another 3 tabs contains an error, which is described in the first post.
I'm using the latest wsl2 bridge and it is reproducible every time.

**Comment by Biswa96** [comment] 2020-09-18 15:06
Apology for late reply. I have merged a pull request which fixes this issue. You could download the artifacts from [Appveyor CI Builds][1]. If I wrote a better error logging this would have been prevented.

Also, if anyone have latest Windows 10 insider builds and/or latest stable Windows 10 builds, please test there also. Insider builds has a different COM interface that the current stable one. So, some code were changed in wslbirdge2 to make sure it 
 works in both stable and insider builds.

[1]: https://ci.appveyor.com/project/Biswa96/wslbridge2

**Comment by silverqx** [comment] 2020-09-18 15:16
> I have merged a pull request which fixes this issue.

I can't reproduce the bug anymore, I fastly tied to close/open with 5 opened consoles and all opened without a problem.

I'm on the latest Win10 Stable v2004 OS build 19041.508.
Great work, thank you ✨🎉

**Comment by Biswa96** [comment] 2020-09-19 18:16
This issue has been fixed by https://github.com/Biswa96/wslbridge2/pull/27 pull request. So closing this. Feel free to open this issue or ask any question you want. Thanks everyone 🙇

**Closed as completed by Biswa96** 2020-09-19 18:16 UTC
Labels: bug :bug:
